using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Unity.VisualScripting;

public class AttributeReader
{
    public static DatabaseConfig BuildDatabaseConfig(DatabaseInformation dbConfigSO)
    {
        DatabaseConfig dbConfig = new DatabaseConfig
        {
            dbType = Enum.GetName(dbConfigSO.dbType.GetType(), dbConfigSO.dbType),
            host = dbConfigSO.host,
            port = dbConfigSO.port,
            username = dbConfigSO.userName,
            password = dbConfigSO.password,
            database = dbConfigSO.databaseName,
            entities = new List<Entity>()
        };

        Assembly assembly = Assembly.GetExecutingAssembly();

        foreach (Type type in assembly.GetTypes())
        {
            var entityAttr = type.GetCustomAttribute<EntityAttribute>();
            if (entityAttr == null) continue;

            Entity entity = new Entity
            {
                name = entityAttr.TableName ?? type.Name,
                columns = new Dictionary<string, Column>(),
            };

            List<Relation> relations = null;


            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var colAttr = prop.GetCustomAttribute<ColumnAttribute>();
                if (colAttr != null)
                {
                    Column column = new Column
                    {
                        type = MapType(prop.PropertyType),
                        primary = colAttr.IsPrimaryKey,
                        generated = colAttr.IsAutoGenerated,
                        length = prop.PropertyType == typeof(string) ? 100 : 0
                    };

                    entity.columns[prop.Name] = column;
                }


                var relAttr = prop.GetCustomAttribute<RelationAttribute>();
                if (relAttr != null)
                {
                    if (relations == null) relations = new List<Relation>();

                    relations.Add(new Relation { type = relAttr.Type, target = relAttr.Target, joinColumn = new JoinColumn { name = relAttr.JoinColumn } });
                }


            }


            if (relations != null && relations.Count > 0)
                entity.relations = relations;

            dbConfig.entities.Add(entity);
        }

        return dbConfig;
    }

    private static string MapType(Type type)
    {
        if (type == typeof(int)) return "integer";
        if (type == typeof(string)) return "varchar";
        if (type == typeof(float) || type == typeof(double)) return "float";
        if (type == typeof(bool)) return "boolean";
        return "text";
    }

    public static string BuildJson(DatabaseInformation dbConfigSO)
    {
        var dbConfig = BuildDatabaseConfig(dbConfigSO);
        return JsonConvert.SerializeObject(dbConfig, Formatting.Indented);
    }
}
