using UnityEngine;

public class ColumnAttribute : PropertyAttribute
{
    public bool IsPrimaryKey { get; }
    public string Name { get; }
    public bool IsAutoGenerated { get; }
    public ColumnAttribute(string columnName, bool primary, bool generated)
    {
        IsPrimaryKey = primary;
        Name = columnName;
        IsAutoGenerated = generated;
    }

    public ColumnAttribute(bool primary, bool generated)
    {
        IsPrimaryKey = primary;
        IsAutoGenerated = generated;
    }

    public ColumnAttribute()
    {
        IsPrimaryKey = false;
        IsAutoGenerated = false;
    }
}
